version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - sqlite3
    networks:
      - backend


  sqlite3:
    container_name: sqlite
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./shortener_app/sqlite3:/root/db/
      - ./shortener.db:/root/db/shortener.db
    ports:
      - '9000:9000' # expose ports - HOST:CONTAINER
    restart: unless-stopped
    networks:
      - backend


  nginx:
    image: nginx:latest
    ports:
      - "81:81"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
    depends_on:
      - app
    networks:
      - backend

networks:
  backend:
    driver: bridge
